# Generated by Django 5.2.7 on 2025-11-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('goodreads', 'goodreads'), ('trakt', 'trakt')], max_length=20),
        ),
    ]
