# Generated by Django 5.2.7 on 2025-11-07 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_activity_activity_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
