# Generated by Django 5.2.7 on 2025-11-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_books_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-read_data']},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['-watched_at']},
        ),
    ]
