# Generated by Django 5.2.7 on 2025-11-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_books_options_alter_movies_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='user',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_date',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_detail',
            field=models.JSONField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='activity',
            name='url',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
