# Generated by Django 5.2.7 on 2025-11-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_remove_movies_user_remove_activity_activity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='backend',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
